import { Header } from '@/components/Header/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FilterContextProvider } from '@/contexts/filter-context'
import { DefaultProviders } from '@/components/default-providers'

const inter = Inter({ 
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultProviders>
          <Header/>
          {children}
        </DefaultProviders>

        </body>
    </html>
  )
}
